### PR TITLE
Add Northern California Earthquake Data Center (NCEDC) for getdata().

### PR DESCRIPTION
**Pull request by kura-okubo**
Hello Josh,

I implemented src/Web/NCEDC.jl to download data from Northern California Earthquake Data Center (NCEDC).
Here is an example:
`S = get_data("NCEDC","BP.RMNB..BP1",s="2002-01-02T00:00:00",t="2002-01-02T01:00:00", src="NCEDC", w=true)`
We need to specify `src="NCEDC"` in the case of request for NCEDC to assign proper NCEDC url.
Note that to request for NCEDC we need `headers = ["Host" => "service.ncedc.org", "User-Agent" => "curl/7.60.0", "Accept" => "*/*"]` when requesting with POST. 
I have done `test SeisIO` and it succeeded, so it wouldn't have any conflict with existing functions.

Best,
Kura

### CODE REVIEW

**Comment by jpjones76** [comment]
Thank you! I really appreciate that you're all trying to help with this. 

I didn't realize that the NCEDC servers aren't true FDSN. They're missing a number of specifications in Table 2 of https://www.fdsn.org/webservices/FDSN-WS-Specifications-1.1.pdf , all of which are mandatory.

Can you confirm that you've tried a manual NCEDC requests with options like `format` (e.g., through their website), and can you confirm that requests with those options fail?

If so, there may be a shorter workaround than duplicating FDSN.jl. What about something like this this?
1. In `FDSNget!`, add `if occursin("ncedc", url) == false` as a condition for writing format and options to the post body.
2. In `get_http_post`, add this as the new first line: `headers =  occursin("ncedc", url) ? ["Host" => "service.ncedc.org", "User-Agent" => "curl/7.60.0", "Accept" => "*/*"] : webhdr`. 
3. In `get_http_post`, change ` req = request(  "POST", url, webhdr, body,` to ` req = request(  "POST", url, headers, body,`.

Miscellaneous questions

1. SeisIO's current file naming convention for FDSN requests is identical to that of IRIS. Why do you that to change to `year_month_JulianDay`?
   - `j` ("Julian day") in that code is the day of the year. Today is Julian day 147 of 2019. 
   - Why not split file names on `"_"` (underscore), parse the year and Julian date, and rename the file based on `j2md(year, jday)`? 

2. NCEDC is already in `seis_www`. Why add it twice?

3. Are there tests to accompany this pull request, or am I expected to write those myself?

**Comment by jpjones76** [comment]
Sorry, after looking at this pull request, it clearly violates the guidelines of CONTRIBUTE.md. There are no tests for the new code of any kind.

- No tests of your own. How am I supposed to know that your code works?

**Comment by jpjones76** [comment]
With sincere apologies, I can't accept this pull request. Please read [CONTRIBUTE.md](https://github.com/jpjones76/SeisIO.jl/blob/master/docs/CONTRIBUTE.md) before making future pull requests.

In particular:
- Please contact me before submitting new features. 
- Please include appropriate tests for new and changed files.
- Please don't push new features to `master`.
- Please ensure that any new functions added are strictly necessary. I was able to connect to the NCEDC by adding or changing about 10 lines of code in FDSN.jl and three lines in 0_essentials.jl, so there was no need to duplicate FDSN.jl as NCEDC.jl.

Finally, but perhaps most importantly: as far as I can tell, the NCEDC server doesn't work. 

All of my data requests (and most of my station XML requests) time out, including requests submitted in my browser with their web form.

```
ERROR: HTTP.ExceptionRequest.StatusError(504, HTTP.Messages.Response:
"""
HTTP/1.1 504 Gateway Time-out
```

Note that this isn't the "headers" issue. 

I've tried from two computers on two networks (Xfinity and Sprint); using Julia's `HTTP` package, SeisIO `get_data`, and two web browsers; and in two operating systems (Windows 10 and Ubuntu 18.04.2 LTS). 

Does their server run on dial-up? Are their computers like the ones in Captain Marvel? I don't understand.

In any case, I can't justify adding this much code to connect to a server that barely works.

**Comment by kura-okubo** [comment]
Hello Josh,

Thank you for dealing with my pull request on "Add Northern California Earthquake Data Center (NCEDC) for getdata(). #14”.
Firstly, I apologize for not following your CONTRIBUTE.md, I didn’t notice that. I will follow the rules for contribution from next.

Those questions below are my faults that I misunderstood overlooked. Please ignore them.
• SeisIO's current file naming convention for FDSN requests is identical to that of IRIS. Who uses year_month_JulianDay?
• j ("Julian day") in that code is the day of the year. Today is Julian day 147 of 2019.
• Why not split file names on "_" (underscore), parse the year and Julian date, and rename the file based on j2md(year, jday)?
• NCEDC is already in seis_www. Why add it twice?

Then, after your suggestions, I realize that we can write it much simpler without duplication of FDSN.jl, so I agree with not merging my pull-requested functions.

The most confusing coincidence is that NCEDC server seems down just after I sent the pull request.
My request did work when writing the codes (05/27 18:00PM), then I couldn't connect the server this morning (5/28 9AM), and it restarts again from 10AM today.
So can I ask you to retry the XML and dataset requests?

The reason I need NCEDC is that we will have a summer internship student, who will use data from BP network with NCEDC data center. (http://ds.iris.edu/gmap/#network=BP&matchtimeseries=true&includeoverlaps=false&level=&format=text&planet=earth)

Overall, SeisIO is a great tool for me to download and processing data. I really like the solid and simple structures (SeisData), which makes my processing scripts much simpler than the other tools.
Downloading station XML with mseed is also very helpful for our purpose.
I’m looking forward to talking to you soon.

Best reagards,
Kurama


-------------------------------------------------
Kurama Okubo
kurama_okubo@fas.harvard.edu<mailto:kurama_okubo@fas.harvard.edu>

Postdoctoral fellow
Harvard University
Department of Earth and Planetary Sciences

20 Oxford Street
Cambridge, MA, 02138
-------------------------------------------------

On May 28, 2019, at 6:18 AM, Joshua Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


With sincere apologies, I can't accept this pull request. Please read CONTRIBUTE.md<https://github.com/jpjones76/SeisIO.jl/blob/master/docs/CONTRIBUTE.md> before making future pull requests.

In particular:

  *   Please contact me before submitting new features.
  *   Please include appropriate tests for new and changed files.
  *   Please don't push new features to master.
  *   Please ensure that any new functions added are strictly necessary. I was able to connect to the NCEDC by adding or changing about 10 lines of code in FDSN.jl and three lines in 0_essentials.jl, so there was no need to duplicate FDSN.jl as NCEDC.jl.

Finally, but perhaps most importantly: as far as I can tell, the NCEDC server doesn't work.

All of my data requests (and most of my station XML requests) time out, including requests submitted in my browser with their web form.

ERROR: HTTP.ExceptionRequest.StatusError(504, HTTP.Messages.Response:
"""
HTTP/1.1 504 Gateway Time-out


Note that this isn't the "headers" issue.

I've tried from two computers on two networks (Xfinity and Sprint); using Julia's HTTP package, SeisIO get_data, and two web browsers; and in two operating systems (Windows 10 and Ubuntu 18.04.2 LTS).

Does their server run on dial-up? Are their computers like the ones in Captain Marvel? I don't understand.

In any case, I can't justify adding this much code to connect to a server that barely works.

**Pull request closed without merging**
