### PR TITLE
Extend demean! and detrend! functions to SeisChannel 

### PR DESCRIPTION
**Pull request by tclements**
This PR allows the demean! and detrend! functions to operate on SeisChannels. This is relevant for ambient noise processing, in which we usually process one specific channel per thread for ease of parallelization.

### CODE REVIEW

**Comment by tclements** [comment]
Adding bandpass, bandstop, lowpass and highpass filters that will operate on AbstractArrays, SeisData and SeisChannel.

**Comment by jpjones76** [comment]
Thank you! I'd like to do some more testing on this pull request before merging it. 

Two issues:

1. These filters assume no time gaps in a channel. That forces this work flow onto users: `... download data --> fill time gaps --> filter ...`. In many situations that order of operations is problematic (e.g., sensors with strong diurnal or tidal effects). So filtering ultimately needs to work on contiguous data segments within each channel, rather than treating the entire channel as contiguous. The same issue arises with most processing operations, unfortunately, which is why I'm slow to create new processing routines.

2. I see that travis-CI failed but I have no idea why the commands in .travis.yml are suddenly a problem. I know that you made no changes to .travis.yml. What's frustrating is that ... neither did I. The commands in that file were generated automatically by the programs that created the encrypted tarball of my 0"restricted" test files. So, unless travis-ci.org changed something fundamental between yesterday and today, I can't explain this.

**Comment by jpjones76** [comment]
Hm. I think I need to switch to manually triggering travis-CI tests of pull requests; .travis.yml works for me and no one else. I think the problem there is that I'm the only one with the key to decrypt my "restricted test files" tarball; indeed I can't share it without violating several redistribution policies. So let's talk about the first point instead.

**Comment by jpjones76** [comment]
Hi Tim,

I really like your proposed methods for detrend! and demean! on SeisChannel objects. Could you please submit them as a separate pull request? I can write tests for their code coverage very easily.

Unfortunately, I can't use the rest of your pull request at this time, so I'm going to close this for now. Some discussion is below.

#### detrend! and demean! for SeisData objects
The proposed changes would create a new SeisChannel for each channel in the SeisData object. This adds ~50% overhead to the computations with no benefit:

```
using BenchmarkTools
S = randSeisData(5, s=1.0)[2:5]
for i = 1:4; S.x[i] += ((0.01*rand()).*(1.0:1.0:Float64(length(S.x[i])))); end
T = deepcopy(S)

# old method 

@benchmark detrend_old!(S)
BenchmarkTools.Trial: 
  memory estimate:  103.11 MiB
  allocs estimate:  474
  --------------
  minimum time:     46.851 ms (8.52% GC)
  median time:      47.320 ms (8.52% GC)
  mean time:        48.707 ms (10.77% GC)
  maximum time:     109.818 ms (59.55% GC)
  --------------
  samples:          103
  evals/sample:     1

# proposed method

@benchmark detrend_new!(T)
BenchmarkTools.Trial: 
  memory estimate:  157.09 MiB
  allocs estimate:  476
  --------------
  minimum time:     67.762 ms (7.74% GC)
  median time:      71.447 ms (8.06% GC)
  mean time:        74.332 ms (10.34% GC)
  maximum time:     199.687 ms (64.52% GC)
  _--------------_
  samples:          68
  evals/sample:     1
```

#### filtering
I need data processing operations in SeisIO to be able to handle time gaps, so that they'll work on each data segment within each channel. These filters implicitly assume no time gaps. The latter forces users into a work flow of `[download data] --> [fill time gaps] --> [filter]`, which is undesirable for some problems. I know that "per-segment" filtering adds a great deal of code complexity, and that's also why I'm slow to create new data processing routines, but adhering to that principle ultimately leads to _much_ more robust code.

**Comment by tclements** [comment]
Great, I'll submit as separate PRs. For the filtering, I agree data gap checking would be nice. The demean, detrend and taper methods _should_ be called before using these filters for proper signal processing.

**Pull request closed without merging**
